const styles = {
  root: {
    minHeight: '100vh',
    background: 'linear-gradient(160deg,var(--color-gradient-start),var(--color-gradient-end))',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px',
    fontFamily: 'Georgia,serif',
  },
  card: {
    background: 'var(--color-card-bg)',
    borderRadius: '20px',
    border: '1.5px solid var(--color-border)',
    padding: '32px 28px',
    maxWidth: '400px',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    boxShadow: '0 8px 32px var(--color-shadow)',
  },
  arabic: {
    fontSize: '36px',
    fontFamily: "'Amiri','Scheherazade New',serif",
    color: 'var(--color-primary)',
    textAlign: 'center',
  },
  title: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: 'var(--color-text)',
    textAlign: 'center',
  },
  body: {
    fontSize: '14px',
    color: 'var(--color-accent)',
    lineHeight: '1.6',
  },
  note: {
    fontSize: '12px',
    color: 'var(--color-text-muted)',
    fontStyle: 'italic',
    lineHeight: '1.5',
  },
  link: {
    color: 'var(--color-link)',
  },
  input: {
    padding: '12px 14px',
    borderRadius: '10px',
    border: '1.5px solid var(--color-border)',
    fontSize: '14px',
    fontFamily: 'monospace',
    background: 'var(--color-input-bg)',
    outline: 'none',
    width: '100%',
    color: 'var(--color-text)',
  },
  btn: {
    padding: '14px',
    borderRadius: '12px',
    border: 'none',
    background: 'var(--color-btn-ai-bg)',
    color: '#fff8ee',
    fontSize: '16px',
    fontWeight: 'bold',
    fontFamily: 'Georgia,serif',
    cursor: 'pointer',
    boxShadow: '0 2px 12px var(--color-shadow-deep)',
  },
  footer: {
    marginTop: '24px',
    textAlign: 'center',
    fontSize: '13px',
  },
  downloadLink: {
    background: 'none',
    border: 'none',
    color: 'var(--color-text-muted)',
    cursor: 'pointer',
    fontSize: '13px',
    fontFamily: 'Georgia,serif',
    textDecoration: 'underline',
    textUnderlineOffset: '2px',
  },
  downloadPanel: {
    marginTop: '12px',
    padding: '16px',
    borderRadius: '12px',
    border: '1px solid var(--color-border)',
    background: 'var(--color-card-bg)',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    alignItems: 'center',
  },
  downloadDesc: {
    fontSize: '12px',
    color: 'var(--color-text-muted)',
    lineHeight: '1.5',
    marginBottom: '4px',
  },
  osBtn: {
    padding: '10px 20px',
    borderRadius: '8px',
    border: '1.5px solid var(--color-border)',
    background: 'var(--color-btn-alpha-bg)',
    color: 'var(--color-text)',
    fontSize: '14px',
    fontFamily: 'Georgia,serif',
    cursor: 'pointer',
    textDecoration: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    width: '100%',
    justifyContent: 'center',
    transition: 'background 0.12s, border-color 0.12s',
  },
  osBtnIcon: {
    fontSize: '16px',
  },
};

export default styles;
