const styles = {
  root: {
    minHeight: '100vh',
    background:
      'linear-gradient(160deg,#fdf0d0 0%,#f5e0b0 50%,#eedfa8 100%)',
    fontFamily: "'Georgia','Times New Roman',serif",
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '16px 12px 32px',
    boxSizing: 'border-box',
    gap: '8px',
    userSelect: 'none',
  },
  header: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '2px',
    position: 'relative',
    width: '100%',
    maxWidth: '520px',
  },
  appTitle: {
    fontSize: '28px',
    fontFamily: "'Amiri','Scheherazade New','Arial Unicode MS',serif",
    color: '#5c2d00',
    textShadow: '0 1px 3px rgba(92,45,0,.2)',
  },
  appSubtitle: {
    fontSize: '11px',
    textTransform: 'uppercase',
    letterSpacing: '.25em',
    color: '#9b6a30',
  },
  keyBtn: {
    background: 'none',
    border: 'none',
    fontSize: '18px',
    color: '#9b6a30',
    cursor: 'pointer',
    padding: '4px',
  },
  keyPanel: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    maxWidth: '520px',
    padding: '8px 14px',
    background: 'rgba(255,255,255,.6)',
    borderRadius: '10px',
    border: '1px solid rgba(180,130,60,.3)',
    boxSizing: 'border-box',
  },
  keyPanelBtn: {
    background: 'none',
    border: '1px solid rgba(180,130,60,.4)',
    borderRadius: '6px',
    padding: '4px 10px',
    fontSize: '12px',
    color: '#6b3800',
    cursor: 'pointer',
  },
  infoBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    maxWidth: '520px',
    padding: '8px 14px',
    background: 'rgba(255,255,255,.5)',
    borderRadius: '12px',
    border: '1px solid rgba(180,130,60,.3)',
    boxSizing: 'border-box',
    gap: '8px',
  },
  letterMeta: {
    display: 'flex',
    flexDirection: 'column',
    minWidth: '60px',
  },
  letterNameLarge: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#3d1800',
  },
  letterRoman: {
    fontSize: '12px',
    color: '#8b5e24',
    fontStyle: 'italic',
  },
  miniPreviews: {
    display: 'flex',
    gap: '12px',
    flex: 1,
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  miniPreview: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '1px',
  },
  miniChar: {
    fontSize: '22px',
    fontFamily: "'Amiri','Scheherazade New',serif",
    color: '#5c2d00',
    lineHeight: 1.4,
    direction: 'rtl',
  },
  miniLabel: {
    fontSize: '8px',
    textTransform: 'uppercase',
    letterSpacing: '.08em',
    color: '#9b6a30',
  },
  progressBadge: {
    fontSize: '12px',
    color: '#9b6a30',
    background: 'rgba(180,130,60,.15)',
    padding: '4px 10px',
    borderRadius: '20px',
    border: '1px solid rgba(180,130,60,.3)',
    whiteSpace: 'nowrap',
  },
  formSwitcher: {
    display: 'flex',
    gap: '8px',
    width: '100%',
    maxWidth: '520px',
    alignItems: 'stretch',
    flexWrap: 'wrap',
  },
  formBtn: {
    flex: '1',
    minWidth: '80px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '3px',
    padding: '10px 8px',
    borderRadius: '14px',
    border: '2px solid rgba(180,130,60,.3)',
    background: 'rgba(255,255,255,.55)',
    cursor: 'pointer',
    transition: 'all .15s',
  },
  formBtnActive: {
    background: 'linear-gradient(150deg,#7a3a0e,#c0703a)',
    border: '2px solid #8b4513',
    boxShadow: '0 3px 12px rgba(139,69,19,.35)',
  },
  formBtnChar: {
    fontSize: '26px',
    fontFamily: "'Amiri','Scheherazade New',serif",
    lineHeight: 1.4,
    direction: 'rtl',
  },
  formBtnName: {
    fontSize: '12px',
    fontWeight: '700',
    letterSpacing: '.04em',
  },
  formBtnSub: {
    fontSize: '9px',
    letterSpacing: '.06em',
    textTransform: 'uppercase',
  },
  nonJoinerNote: {
    width: '100%',
    textAlign: 'center',
    fontSize: '11px',
    color: '#9b6a30',
    fontStyle: 'italic',
    padding: '6px 0 2px',
  },
  hintRow: {
    display: 'flex',
    gap: '8px',
    alignItems: 'flex-start',
    width: '100%',
    maxWidth: '520px',
    padding: '0 4px',
    boxSizing: 'border-box',
  },
  hintIcon: {
    color: '#c0803a',
    fontSize: '12px',
    marginTop: '2px',
    flexShrink: 0,
  },
  hintText: {
    fontSize: '12px',
    color: '#6b4010',
    lineHeight: '1.6',
  },
  canvasWrap: {
    position: 'relative',
    width: '100%',
    maxWidth: '520px',
    aspectRatio: '1/1',
    background: 'rgba(255,252,240,.85)',
    borderRadius: '16px',
    border: '2px solid rgba(180,130,60,.4)',
    boxShadow:
      '0 4px 24px rgba(100,60,0,.12),inset 0 1px 0 rgba(255,255,255,.8)',
    overflow: 'hidden',
    touchAction: 'none',
  },
  ghostLetter: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '200px',
    fontFamily: "'Amiri','Scheherazade New','Arial Unicode MS',serif",
    color: 'rgba(139,90,43,.18)',
    pointerEvents: 'none',
    lineHeight: 1.2,
    direction: 'rtl',
    userSelect: 'none',
  },
  canvas: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    touchAction: 'none',
    cursor: 'crosshair',
    borderRadius: '14px',
  },
  rtlGuide: {
    position: 'absolute',
    bottom: '8px',
    right: '12px',
    fontSize: '10px',
    color: 'rgba(120,80,30,.45)',
    letterSpacing: '.05em',
    pointerEvents: 'none',
  },
  controls: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    justifyContent: 'center',
    width: '100%',
    maxWidth: '520px',
  },
  btn: {
    padding: '10px 18px',
    borderRadius: '10px',
    border: 'none',
    fontSize: '14px',
    fontFamily: "'Georgia',serif",
    cursor: 'pointer',
    fontWeight: '600',
    letterSpacing: '.02em',
  },
  btnNav: {
    background: 'rgba(255,255,255,.6)',
    color: '#5c2d00',
    border: '1px solid rgba(180,130,60,.35)',
    flex: '1',
    minWidth: '80px',
  },
  btnClear: {
    background: 'rgba(220,180,120,.3)',
    color: '#6b3800',
    border: '1px solid rgba(180,130,60,.4)',
    flex: '1',
  },
  btnShowMe: {
    background: 'rgba(139,69,19,.1)',
    color: '#7a3a0e',
    border: '1px solid rgba(180,130,60,.4)',
    flex: '1',
    minWidth: '90px',
  },
  btnAI: {
    background: 'linear-gradient(135deg,#8b4513,#c0703a)',
    color: '#fff8ee',
    boxShadow: '0 2px 12px rgba(139,69,19,.35)',
    flex: '2',
    minWidth: '120px',
  },
  feedbackBox: {
    width: '100%',
    maxWidth: '520px',
    background: 'rgba(255,252,240,.9)',
    border: '1px solid rgba(180,130,60,.4)',
    borderRadius: '12px',
    padding: '14px 18px',
    boxSizing: 'border-box',
  },
  feedbackError: {
    background: 'rgba(255,235,235,.9)',
    border: '1px solid rgba(200,100,100,.4)',
    color: '#8b2000',
    fontSize: '14px',
  },
  feedbackLabel: {
    fontSize: '10px',
    textTransform: 'uppercase',
    letterSpacing: '.2em',
    color: '#9b6a30',
    marginBottom: '8px',
  },
  feedbackText: {
    margin: 0,
    fontSize: '14px',
    color: '#3d1800',
    lineHeight: '1.7',
  },
  alphabetRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '4px',
    justifyContent: 'center',
    width: '100%',
    maxWidth: '520px',
    padding: '8px',
    background: 'rgba(255,255,255,.4)',
    borderRadius: '12px',
    border: '1px solid rgba(180,130,60,.2)',
    boxSizing: 'border-box',
  },
  alphaBtn: {
    width: '34px',
    height: '34px',
    border: '1px solid rgba(180,130,60,.25)',
    borderRadius: '8px',
    background: 'rgba(255,255,255,.5)',
    fontSize: '18px',
    cursor: 'pointer',
    color: '#4a2000',
    fontFamily: "'Amiri','Scheherazade New',serif",
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  alphaBtnActive: {
    background: 'linear-gradient(135deg,#8b4513,#c0703a)',
    color: '#fff8ee',
    border: '1px solid #8b4513',
    boxShadow: '0 2px 8px rgba(139,69,19,.3)',
  },
  completedBadge: {
    display: 'inline-block',
    marginLeft: '10px',
    fontSize: '10px',
    background: 'rgba(139,69,19,.15)',
    color: '#7a3a0e',
    padding: '2px 8px',
    borderRadius: '20px',
    border: '1px solid rgba(139,69,19,.25)',
    verticalAlign: 'middle',
    letterSpacing: '.04em',
  },
  dotComplete: {
    position: 'absolute',
    bottom: '3px',
    right: '3px',
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    background: '#5a9e4e',
    display: 'block',
  },
  dotStarted: {
    position: 'absolute',
    bottom: '3px',
    right: '3px',
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    background: '#c0703a',
    display: 'block',
  },
  historyToggle: {
    background: 'none',
    border: 'none',
    padding: '6px 2px',
    fontSize: '12px',
    color: '#9b6a30',
    cursor: 'pointer',
    width: '100%',
    textAlign: 'left',
    letterSpacing: '.03em',
  },
  historyPanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    paddingBottom: '4px',
  },
  historyEntry: {
    background: 'rgba(255,252,240,.7)',
    border: '1px solid rgba(180,130,60,.25)',
    borderRadius: '10px',
    padding: '10px 14px',
  },
  historyDate: {
    fontSize: '10px',
    color: '#9b6a30',
    textTransform: 'uppercase',
    letterSpacing: '.1em',
    marginBottom: '6px',
  },
  historyText: {
    margin: 0,
    fontSize: '13px',
    color: '#3d1800',
    lineHeight: '1.65',
  },
  offlineBanner: {
    width: '100%',
    maxWidth: '520px',
    background: 'rgba(180,130,60,.2)',
    border: '1px solid rgba(180,130,60,.5)',
    borderRadius: '8px',
    padding: '8px 14px',
    fontSize: '12px',
    color: '#6b3800',
    textAlign: 'center',
    boxSizing: 'border-box',
  },

  /* ─── Header buttons row ─────────────────────────────── */
  headerButtons: {
    position: 'absolute',
    top: 0,
    right: 0,
    display: 'flex',
    gap: '4px',
    alignItems: 'center',
  },

  /* ─── Lesson mode toggle ─────────────────────────────── */
  lessonToggle: {
    background: 'none',
    border: '1px solid transparent',
    fontSize: '16px',
    cursor: 'pointer',
    padding: '3px 6px',
    borderRadius: '6px',
    transition: 'all .15s',
  },
  lessonToggleActive: {
    background: 'rgba(139,69,19,.12)',
    border: '1px solid rgba(180,130,60,.4)',
  },
  lessonBanner: {
    width: '100%',
    maxWidth: '520px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '6px 14px',
    background: 'rgba(139,69,19,.08)',
    borderRadius: '8px',
    border: '1px solid rgba(180,130,60,.25)',
    boxSizing: 'border-box',
  },
  lessonGroupName: {
    fontSize: '13px',
    fontWeight: '700',
    color: '#5c2d00',
  },
  lessonGroupDesc: {
    fontSize: '11px',
    color: '#9b6a30',
    fontStyle: 'italic',
  },

  /* ─── Comparison view ────────────────────────────────── */
  comparisonWrap: {
    width: '100%',
    maxWidth: '520px',
    display: 'flex',
    gap: '10px',
    boxSizing: 'border-box',
  },
  comparisonPane: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '6px',
  },
  comparisonLabel: {
    fontSize: '10px',
    textTransform: 'uppercase',
    letterSpacing: '.15em',
    color: '#9b6a30',
  },
  comparisonRef: {
    width: '100%',
    aspectRatio: '1/1',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(255,252,240,.85)',
    borderRadius: '12px',
    border: '2px solid rgba(180,130,60,.3)',
    fontSize: '140px',
    fontFamily: "'Amiri','Scheherazade New','Arial Unicode MS',serif",
    color: '#5c2d00',
    direction: 'rtl',
    lineHeight: 1.2,
  },
  comparisonAttempt: {
    width: '100%',
    aspectRatio: '1/1',
    borderRadius: '12px',
    border: '2px solid rgba(180,130,60,.3)',
    background: 'rgba(255,252,240,.85)',
    objectFit: 'contain',
  },
  comparisonToggle: {
    background: 'none',
    border: '1px solid rgba(180,130,60,.3)',
    borderRadius: '8px',
    padding: '6px 14px',
    fontSize: '12px',
    color: '#6b3800',
    cursor: 'pointer',
    letterSpacing: '.03em',
  },

  /* ─── Mode tabs (Letters / Words) ──────────────────────── */
  modeTabs: {
    display: 'flex',
    gap: '6px',
    width: '100%',
    maxWidth: '520px',
  },
  modeTab: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '8px 12px',
    borderRadius: '10px',
    border: '1.5px solid rgba(180,130,60,.25)',
    background: 'rgba(255,255,255,.4)',
    fontSize: '13px',
    fontWeight: '600',
    color: '#6b3800',
    cursor: 'pointer',
    letterSpacing: '.04em',
    transition: 'all .15s',
  },
  modeTabActive: {
    background: 'linear-gradient(150deg,#7a3a0e,#c0703a)',
    border: '1.5px solid #8b4513',
    color: '#fff8ee',
    boxShadow: '0 2px 8px rgba(139,69,19,.25)',
  },

  /* ─── Ghost word (word practice mode) ────────────────── */
  ghostWord: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '100px',
    fontFamily: "'Amiri','Scheherazade New','Arial Unicode MS',serif",
    color: 'rgba(139,90,43,.18)',
    pointerEvents: 'none',
    lineHeight: 1.2,
    direction: 'rtl',
    userSelect: 'none',
    padding: '0 20px',
  },

  /* ─── Word buttons in bottom row ─────────────────────── */
  wordBtn: {
    minWidth: '50px',
    height: '34px',
    border: '1px solid rgba(180,130,60,.25)',
    borderRadius: '8px',
    background: 'rgba(255,255,255,.5)',
    fontSize: '16px',
    cursor: 'pointer',
    color: '#4a2000',
    fontFamily: "'Amiri','Scheherazade New',serif",
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0 10px',
    position: 'relative',
  },

  /* ─── Score stars ─────────────────────────────────────── */
  scoreRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    marginBottom: '8px',
  },
  starFilled: {
    fontSize: '20px',
    color: '#c0703a',
  },
  starEmpty: {
    fontSize: '20px',
    color: 'rgba(180,130,60,.25)',
  },
  scoreLabel: {
    fontSize: '11px',
    color: '#9b6a30',
    marginLeft: '6px',
  },
};

export default styles;
