const styles = {
  root: {
    minHeight: '100vh',
    background: 'linear-gradient(160deg,var(--color-gradient-start) 0%,var(--color-gradient-mid) 50%,var(--color-gradient-end) 100%)',
    fontFamily: "'Georgia','Times New Roman',serif",
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '16px 12px 32px',
    boxSizing: 'border-box',
    gap: '8px',
    userSelect: 'none',
  },
  header: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '2px',
    position: 'relative',
    width: '100%',
    maxWidth: '520px',
  },
  appTitle: {
    fontSize: '28px',
    fontFamily: "'Amiri','Scheherazade New','Arial Unicode MS',serif",
    color: 'var(--color-primary)',
    textShadow: '0 1px 3px var(--color-shadow)',
  },
  appSubtitle: {
    fontSize: '11px',
    textTransform: 'uppercase',
    letterSpacing: '.25em',
    color: 'var(--color-text-muted)',
  },
  keyBtn: {
    background: 'none',
    border: 'none',
    fontSize: '18px',
    color: 'var(--color-text-muted)',
    cursor: 'pointer',
    padding: '4px',
  },
  keyPanel: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    maxWidth: '520px',
    padding: '8px 14px',
    background: 'var(--color-surface-solid)',
    borderRadius: '10px',
    border: '1px solid var(--color-border)',
    boxSizing: 'border-box',
  },
  keyPanelBtn: {
    background: 'none',
    border: '1px solid var(--color-border)',
    borderRadius: '6px',
    padding: '4px 10px',
    fontSize: '12px',
    color: 'var(--color-accent)',
    cursor: 'pointer',
  },
  infoBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    maxWidth: '520px',
    padding: '8px 14px',
    background: 'var(--color-surface-solid)',
    borderRadius: '12px',
    border: '1px solid var(--color-border)',
    boxSizing: 'border-box',
    gap: '8px',
  },
  letterMeta: {
    display: 'flex',
    flexDirection: 'column',
    minWidth: '60px',
  },
  letterNameLarge: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: 'var(--color-text)',
  },
  letterRoman: {
    fontSize: '12px',
    color: 'var(--color-text-muted)',
    fontStyle: 'italic',
  },
  miniPreviews: {
    display: 'flex',
    gap: '12px',
    flex: 1,
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  miniPreview: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '1px',
  },
  miniChar: {
    fontSize: '22px',
    fontFamily: "'Amiri','Scheherazade New',serif",
    color: 'var(--color-primary)',
    lineHeight: 1.4,
    direction: 'rtl',
  },
  miniLabel: {
    fontSize: '8px',
    textTransform: 'uppercase',
    letterSpacing: '.08em',
    color: 'var(--color-text-muted)',
  },
  progressBadge: {
    fontSize: '12px',
    color: 'var(--color-text-muted)',
    background: 'var(--color-progress-badge-bg)',
    padding: '4px 10px',
    borderRadius: '20px',
    border: '1px solid var(--color-border)',
    whiteSpace: 'nowrap',
  },
  formSwitcher: {
    display: 'flex',
    gap: '8px',
    width: '100%',
    maxWidth: '520px',
    alignItems: 'stretch',
    flexWrap: 'wrap',
  },
  formBtn: {
    flex: '1',
    minWidth: '80px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '3px',
    padding: '10px 8px',
    borderRadius: '14px',
    border: '2px solid var(--color-border)',
    background: 'var(--color-surface-solid)',
    cursor: 'pointer',
    transition: 'all .15s',
  },
  formBtnActive: {
    background: 'var(--color-form-active-bg)',
    border: '2px solid var(--color-accent)',
    boxShadow: '0 3px 12px var(--color-shadow-deep)',
  },
  formBtnChar: {
    fontSize: '26px',
    fontFamily: "'Amiri','Scheherazade New',serif",
    lineHeight: 1.4,
    direction: 'rtl',
  },
  formBtnName: {
    fontSize: '12px',
    fontWeight: '700',
    letterSpacing: '.04em',
  },
  formBtnSub: {
    fontSize: '9px',
    letterSpacing: '.06em',
    textTransform: 'uppercase',
  },
  nonJoinerNote: {
    width: '100%',
    textAlign: 'center',
    fontSize: '11px',
    color: 'var(--color-text-muted)',
    fontStyle: 'italic',
    padding: '6px 0 2px',
  },
  hintRow: {
    display: 'flex',
    gap: '8px',
    alignItems: 'flex-start',
    width: '100%',
    maxWidth: '520px',
    padding: '0 4px',
    boxSizing: 'border-box',
  },
  hintIcon: {
    color: 'var(--color-accent-light)',
    fontSize: '12px',
    marginTop: '2px',
    flexShrink: 0,
  },
  hintText: {
    fontSize: '12px',
    color: 'var(--color-text-soft)',
    lineHeight: '1.6',
  },
  canvasWrap: {
    position: 'relative',
    width: '100%',
    maxWidth: '520px',
    aspectRatio: '1/1',
    background: 'var(--color-canvas-bg)',
    borderRadius: '16px',
    border: '2px solid var(--color-canvas-border)',
    boxShadow: '0 4px 24px var(--color-shadow),inset 0 1px 0 var(--color-surface-hover)',
    overflow: 'hidden',
    touchAction: 'none',
  },
  ghostLetter: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '200px',
    fontFamily: "'Amiri','Scheherazade New','Arial Unicode MS',serif",
    color: 'var(--color-ghost)',
    pointerEvents: 'none',
    lineHeight: 1.2,
    direction: 'rtl',
    userSelect: 'none',
  },
  canvas: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    touchAction: 'none',
    cursor: 'crosshair',
    borderRadius: '14px',
  },
  rtlGuide: {
    position: 'absolute',
    bottom: '8px',
    right: '12px',
    fontSize: '10px',
    color: 'var(--color-ghost)',
    letterSpacing: '.05em',
    pointerEvents: 'none',
  },
  controls: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    justifyContent: 'center',
    width: '100%',
    maxWidth: '520px',
  },
  btn: {
    padding: '10px 18px',
    borderRadius: '10px',
    border: 'none',
    fontSize: '14px',
    fontFamily: "'Georgia',serif",
    cursor: 'pointer',
    fontWeight: '600',
    letterSpacing: '.02em',
  },
  btnNav: {
    background: 'var(--color-btn-nav-bg)',
    color: 'var(--color-primary)',
    border: '1px solid var(--color-border)',
    flex: '1',
    minWidth: '80px',
  },
  btnClear: {
    background: 'var(--color-btn-clear-bg)',
    color: 'var(--color-accent)',
    border: '1px solid var(--color-border)',
    flex: '1',
  },
  btnShowMe: {
    background: 'var(--color-btn-showme-bg)',
    color: 'var(--color-accent-warm)',
    border: '1px solid var(--color-border)',
    flex: '1',
    minWidth: '90px',
  },
  btnAI: {
    background: 'var(--color-btn-ai-bg)',
    color: '#fff8ee',
    boxShadow: '0 2px 12px var(--color-shadow-deep)',
    flex: '2',
    minWidth: '120px',
  },
  feedbackBox: {
    width: '100%',
    maxWidth: '520px',
    background: 'var(--color-surface)',
    border: '1px solid var(--color-canvas-border)',
    borderRadius: '12px',
    padding: '14px 18px',
    boxSizing: 'border-box',
  },
  feedbackError: {
    background: 'var(--color-feedback-error-bg)',
    border: '1px solid var(--color-feedback-error-border)',
    color: 'var(--color-feedback-error-text)',
    fontSize: '14px',
  },
  feedbackLabel: {
    fontSize: '10px',
    textTransform: 'uppercase',
    letterSpacing: '.2em',
    color: 'var(--color-text-muted)',
    marginBottom: '8px',
  },
  feedbackText: {
    margin: 0,
    fontSize: '14px',
    color: 'var(--color-text)',
    lineHeight: '1.7',
  },
  alphabetRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '4px',
    justifyContent: 'center',
    width: '100%',
    maxWidth: '520px',
    padding: '8px',
    background: 'var(--color-surface-solid)',
    borderRadius: '12px',
    border: '1px solid var(--color-border)',
    boxSizing: 'border-box',
  },
  alphaBtn: {
    width: '34px',
    height: '34px',
    border: '1px solid var(--color-border)',
    borderRadius: '8px',
    background: 'var(--color-btn-alpha-bg)',
    fontSize: '18px',
    cursor: 'pointer',
    color: 'var(--color-text)',
    fontFamily: "'Amiri','Scheherazade New',serif",
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  alphaBtnActive: {
    background: 'var(--color-form-active-bg)',
    color: '#fff8ee',
    border: '1px solid var(--color-accent)',
    boxShadow: '0 2px 8px var(--color-shadow-deep)',
  },
  completedBadge: {
    display: 'inline-block',
    marginLeft: '10px',
    fontSize: '10px',
    background: 'var(--color-accent-warm)',
    color: 'var(--color-text-muted)',
    padding: '2px 8px',
    borderRadius: '20px',
    border: '1px solid var(--color-border)',
    verticalAlign: 'middle',
    letterSpacing: '.04em',
  },
  dotComplete: {
    position: 'absolute',
    bottom: '3px',
    right: '3px',
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    background: 'var(--color-dot-complete)',
    display: 'block',
  },
  dotStarted: {
    position: 'absolute',
    bottom: '3px',
    right: '3px',
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    background: 'var(--color-dot-started)',
    display: 'block',
  },
  historyToggle: {
    background: 'none',
    border: 'none',
    padding: '6px 2px',
    fontSize: '12px',
    color: 'var(--color-text-muted)',
    cursor: 'pointer',
    width: '100%',
    textAlign: 'left',
    letterSpacing: '.03em',
  },
  historyPanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    paddingBottom: '4px',
  },
  historyEntry: {
    background: 'var(--color-surface)',
    border: '1px solid var(--color-border)',
    borderRadius: '10px',
    padding: '10px 14px',
  },
  historyDate: {
    fontSize: '10px',
    color: 'var(--color-text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '.1em',
    marginBottom: '6px',
  },
  historyText: {
    margin: 0,
    fontSize: '13px',
    color: 'var(--color-text)',
    lineHeight: '1.65',
  },
  offlineBanner: {
    width: '100%',
    maxWidth: '520px',
    background: 'var(--color-offline-bg)',
    border: '1px solid var(--color-border-strong)',
    borderRadius: '8px',
    padding: '8px 14px',
    fontSize: '12px',
    color: 'var(--color-accent)',
    textAlign: 'center',
    boxSizing: 'border-box',
  },

  /* ─── Header buttons row ─────────────────────────────── */
  headerButtons: {
    position: 'absolute',
    top: 0,
    right: 0,
    display: 'flex',
    gap: '4px',
    alignItems: 'center',
  },

  /* ─── Lesson mode toggle ─────────────────────────────── */
  lessonToggle: {
    background: 'none',
    border: '1px solid transparent',
    fontSize: '16px',
    cursor: 'pointer',
    padding: '3px 6px',
    borderRadius: '6px',
    transition: 'all .15s',
  },
  lessonToggleActive: {
    background: 'var(--color-btn-showme-bg)',
    border: '1px solid var(--color-border)',
  },
  lessonBanner: {
    width: '100%',
    maxWidth: '520px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '6px 14px',
    background: 'var(--color-btn-showme-bg)',
    borderRadius: '8px',
    border: '1px solid var(--color-border)',
    boxSizing: 'border-box',
  },
  lessonGroupName: {
    fontSize: '13px',
    fontWeight: '700',
    color: 'var(--color-primary)',
  },
  lessonGroupDesc: {
    fontSize: '11px',
    color: 'var(--color-text-muted)',
    fontStyle: 'italic',
  },

  /* ─── Comparison view ────────────────────────────────── */
  comparisonWrap: {
    width: '100%',
    maxWidth: '520px',
    display: 'flex',
    gap: '10px',
    boxSizing: 'border-box',
  },
  comparisonPane: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '6px',
  },
  comparisonLabel: {
    fontSize: '10px',
    textTransform: 'uppercase',
    letterSpacing: '.15em',
    color: 'var(--color-text-muted)',
  },
  comparisonRef: {
    width: '100%',
    aspectRatio: '1/1',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'var(--color-canvas-bg)',
    borderRadius: '12px',
    border: '2px solid var(--color-border)',
    fontSize: '140px',
    fontFamily: "'Amiri','Scheherazade New','Arial Unicode MS',serif",
    color: 'var(--color-primary)',
    direction: 'rtl',
    lineHeight: 1.2,
  },
  comparisonAttempt: {
    width: '100%',
    aspectRatio: '1/1',
    borderRadius: '12px',
    border: '2px solid var(--color-border)',
    background: 'var(--color-canvas-bg)',
    objectFit: 'contain',
  },
  comparisonToggle: {
    background: 'none',
    border: '1px solid var(--color-border)',
    borderRadius: '8px',
    padding: '6px 14px',
    fontSize: '12px',
    color: 'var(--color-accent)',
    cursor: 'pointer',
    letterSpacing: '.03em',
  },

  /* ─── Mode tabs (Letters / Words) ──────────────────────── */
  modeTabs: {
    display: 'flex',
    gap: '6px',
    width: '100%',
    maxWidth: '520px',
  },
  modeTab: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '8px 12px',
    borderRadius: '10px',
    border: '1.5px solid var(--color-border)',
    background: 'var(--color-surface-solid)',
    fontSize: '13px',
    fontWeight: '600',
    color: 'var(--color-accent)',
    cursor: 'pointer',
    letterSpacing: '.04em',
    transition: 'all .15s',
  },
  modeTabActive: {
    background: 'var(--color-form-active-bg)',
    border: '1.5px solid var(--color-accent)',
    color: '#fff8ee',
    boxShadow: '0 2px 8px var(--color-shadow-deep)',
  },

  /* ─── Ghost word (word practice mode) ────────────────── */
  ghostWord: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '100px',
    fontFamily: "'Amiri','Scheherazade New','Arial Unicode MS',serif",
    color: 'var(--color-ghost)',
    pointerEvents: 'none',
    lineHeight: 1.2,
    direction: 'rtl',
    userSelect: 'none',
    padding: '0 20px',
  },

  /* ─── Word buttons in bottom row ─────────────────────── */
  wordBtn: {
    minWidth: '50px',
    height: '34px',
    border: '1px solid var(--color-border)',
    borderRadius: '8px',
    background: 'var(--color-btn-alpha-bg)',
    fontSize: '16px',
    cursor: 'pointer',
    color: 'var(--color-text)',
    fontFamily: "'Amiri','Scheherazade New',serif",
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0 10px',
    position: 'relative',
  },

  /* ─── Save / Share buttons ───────────────────────────── */
  btnSave: {
    background: 'var(--color-btn-clear-bg)',
    color: 'var(--color-accent)',
    border: '1px solid var(--color-border)',
    flex: '1',
  },
  btnShare: {
    background: 'var(--color-btn-nav-bg)',
    color: 'var(--color-primary)',
    border: '1px solid var(--color-border)',
    flex: '1',
  },

  /* ─── Review dashboard ────────────────────────────────── */
  reviewDash: {
    width: '100%',
    maxWidth: '520px',
    background: 'var(--color-surface-solid)',
    border: '1px solid var(--color-border)',
    borderRadius: '12px',
    padding: '16px 18px',
    boxSizing: 'border-box',
  },
  reviewHeader: {
    fontSize: '11px',
    textTransform: 'uppercase',
    letterSpacing: '.2em',
    color: 'var(--color-text-muted)',
    marginBottom: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  reviewCount: {
    display: 'inline-block',
    background: 'var(--color-accent)',
    color: '#fff',
    fontSize: '11px',
    fontWeight: '700',
    padding: '1px 7px',
    borderRadius: '20px',
    letterSpacing: '0',
    textTransform: 'none',
  },
  reviewEmpty: {
    textAlign: 'center',
    color: 'var(--color-text-soft)',
    fontSize: '14px',
    padding: '28px 0',
    lineHeight: 1.6,
  },
  reviewGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    justifyContent: 'center',
  },
  reviewTile: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '2px',
    width: '68px',
    padding: '10px 4px',
    borderRadius: '10px',
    border: '1.5px solid var(--color-border)',
    background: 'var(--color-surface)',
    cursor: 'pointer',
    transition: 'all .15s',
  },
  reviewTileChar: {
    fontSize: '32px',
    fontFamily: "'Amiri','Scheherazade New',serif",
    color: 'var(--color-primary)',
    lineHeight: 1.3,
    direction: 'rtl',
  },
  reviewTileName: {
    fontSize: '9px',
    color: 'var(--color-text-muted)',
    textAlign: 'center',
    letterSpacing: '.03em',
  },
  reviewTileForm: {
    fontSize: '8px',
    color: 'var(--color-accent)',
    textTransform: 'uppercase',
    letterSpacing: '.06em',
    textAlign: 'center',
  },

  /* ─── Score stars ─────────────────────────────────────── */
  scoreRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    marginBottom: '8px',
  },
  starFilled: {
    fontSize: '20px',
    color: 'var(--color-star-filled)',
  },
  starEmpty: {
    fontSize: '20px',
    color: 'var(--color-star-empty)',
  },
  scoreLabel: {
    fontSize: '11px',
    color: 'var(--color-text-muted)',
    marginLeft: '6px',
  },
};

export default styles;
