const styles = {
  root: {
    minHeight: '100vh',
    background:
      'linear-gradient(160deg,var(--color-gradient-start) 0%,var(--color-gradient-mid) 50%,var(--color-gradient-end) 100%)',
    fontFamily: "'Georgia','Times New Roman',serif",
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '16px 12px 32px',
    boxSizing: 'border-box',
    gap: '8px',
    userSelect: 'none',
  },
  header: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '2px',
    position: 'relative',
    width: '100%',
    maxWidth: '520px',
  },
  appTitle: {
    fontSize: '28px',
    color: 'var(--color-primary)',
    textShadow: '0 1px 3px var(--color-shadow)',
  },
  appSubtitle: {
    fontSize: '11px',
    textTransform: 'uppercase',
    letterSpacing: '.25em',
    color: 'var(--color-text-muted)',
  },
  keyBtn: {
    background: 'none',
    border: 'none',
    fontSize: '18px',
    color: 'var(--color-text-muted)',
    cursor: 'pointer',
    padding: '4px',
  },
  keyPanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    width: '100%',
    maxWidth: '560px',
    padding: '16px 18px',
    background: 'var(--color-surface-solid)',
    borderRadius: '12px',
    border: '1px solid var(--color-border)',
    boxSizing: 'border-box',
  },
  settingsSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    width: '100%',
  },
  settingsSectionTitle: {
    fontSize: '11px',
    textTransform: 'uppercase',
    letterSpacing: '.12em',
    color: 'var(--color-text-muted)',
  },
  settingsRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap',
  },
  settingsToggleBtn: {
    padding: '6px 10px',
    border: '1px solid var(--color-border)',
    borderRadius: '6px',
    background: 'var(--color-surface-solid)',
    fontSize: '12px',
    color: 'var(--color-text)',
    cursor: 'pointer',
  },
  keyPanelBtn: {
    background: 'none',
    border: '1px solid var(--color-border)',
    borderRadius: '6px',
    padding: '4px 10px',
    fontSize: '12px',
    color: 'var(--color-accent)',
    cursor: 'pointer',
  },
  infoBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    maxWidth: '520px',
    padding: '8px 14px',
    background: 'var(--color-surface-solid)',
    borderRadius: '12px',
    border: '1px solid var(--color-border)',
    boxSizing: 'border-box',
    gap: '8px',
  },
  letterMeta: {
    display: 'flex',
    flexDirection: 'column',
    minWidth: '60px',
  },
  letterNameLarge: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: 'var(--color-text)',
  },
  letterRoman: {
    fontSize: '12px',
    color: 'var(--color-text-muted)',
    fontStyle: 'italic',
  },
  miniPreviews: {
    display: 'flex',
    gap: '12px',
    flex: 1,
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  miniPreview: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '1px',
  },
  miniChar: {
    fontSize: '22px',
    color: 'var(--color-primary)',
    lineHeight: 1.4,
    direction: 'rtl',
  },
  miniLabel: {
    fontSize: '8px',
    textTransform: 'uppercase',
    letterSpacing: '.08em',
    color: 'var(--color-text-muted)',
  },
  progressBadge: {
    fontSize: '12px',
    color: 'var(--color-text-muted)',
    background: 'var(--color-progress-badge-bg)',
    padding: '4px 10px',
    borderRadius: '20px',
    border: '1px solid var(--color-border)',
    whiteSpace: 'nowrap',
  },
  formSwitcher: {
    display: 'flex',
    gap: '8px',
    width: '100%',
    maxWidth: '520px',
    alignItems: 'stretch',
    flexWrap: 'wrap',
  },
  formBtn: {
    flex: '1',
    minWidth: '80px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '3px',
    padding: '10px 8px',
    borderRadius: '14px',
    border: '2px solid var(--color-border)',
    background: 'var(--color-surface-solid)',
    cursor: 'pointer',
    transition: 'all .15s',
  },
  formBtnActive: {
    background: 'var(--color-form-active-bg)',
    border: '2px solid var(--color-accent)',
    boxShadow: '0 3px 12px var(--color-shadow-deep)',
  },
  formBtnChar: {
    fontSize: '26px',
    lineHeight: 1.4,
    direction: 'rtl',
  },
  formBtnName: {
    fontSize: '12px',
    fontWeight: '700',
    letterSpacing: '.04em',
  },
  formBtnSub: {
    fontSize: '9px',
    letterSpacing: '.06em',
    textTransform: 'uppercase',
  },
  nonJoinerNote: {
    width: '100%',
    textAlign: 'center',
    fontSize: '11px',
    color: 'var(--color-text-muted)',
    fontStyle: 'italic',
    padding: '6px 0 2px',
  },
  hintRow: {
    display: 'flex',
    gap: '8px',
    alignItems: 'flex-start',
    width: '100%',
    maxWidth: '520px',
    padding: '0 4px',
    boxSizing: 'border-box',
  },
  hintIcon: {
    color: 'var(--color-accent-light)',
    fontSize: '12px',
    marginTop: '2px',
    flexShrink: 0,
  },
  hintText: {
    fontSize: '12px',
    color: 'var(--color-text-soft)',
    lineHeight: '1.6',
  },
  canvasWrap: {
    position: 'relative',
    width: '100%',
    maxWidth: '520px',
    aspectRatio: '1/1',
    background: 'var(--color-canvas-bg)',
    borderRadius: '16px',
    border: '2px solid var(--color-canvas-border)',
    boxShadow: '0 4px 24px var(--color-shadow),inset 0 1px 0 var(--color-surface-hover)',
    overflow: 'hidden',
    touchAction: 'none',
  },
  canvas: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    touchAction: 'none',
    cursor: 'crosshair',
    borderRadius: '14px',
  },
  rtlGuide: {
    position: 'absolute',
    bottom: '8px',
    right: '12px',
    fontSize: '10px',
    color: 'var(--color-ghost)',
    letterSpacing: '.05em',
    pointerEvents: 'none',
  },
  controls: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    justifyContent: 'center',
    width: '100%',
    maxWidth: '520px',
  },
  btn: {
    padding: '10px 18px',
    borderRadius: '10px',
    border: 'none',
    fontSize: '14px',
    fontFamily: "'Georgia',serif",
    cursor: 'pointer',
    fontWeight: '600',
    letterSpacing: '.02em',
  },
  btnNav: {
    background: 'var(--color-btn-nav-bg)',
    color: 'var(--color-primary)',
    border: '1px solid var(--color-border)',
    flex: '1',
    minWidth: '80px',
  },
  btnClear: {
    background: 'var(--color-btn-clear-bg)',
    color: 'var(--color-accent)',
    border: '1px solid var(--color-border)',
    flex: '1',
  },
  btnShowMe: {
    background: 'var(--color-btn-showme-bg)',
    color: 'var(--color-accent-warm)',
    border: '1px solid var(--color-border)',
    flex: '1',
    minWidth: '90px',
  },
  btnAI: {
    background: 'var(--color-btn-ai-bg)',
    color: '#fff8ee',
    boxShadow: '0 2px 12px var(--color-shadow-deep)',
    flex: '2',
    minWidth: '120px',
  },
  feedbackBox: {
    width: '100%',
    maxWidth: '520px',
    background: 'var(--color-surface)',
    border: '1px solid var(--color-canvas-border)',
    borderRadius: '12px',
    padding: '14px 18px',
    boxSizing: 'border-box',
  },
  feedbackError: {
    background: 'var(--color-feedback-error-bg)',
    border: '1px solid var(--color-feedback-error-border)',
    color: 'var(--color-feedback-error-text)',
    fontSize: '14px',
  },
  feedbackLabel: {
    fontSize: '10px',
    textTransform: 'uppercase',
    letterSpacing: '.2em',
    color: 'var(--color-text-muted)',
    marginBottom: '8px',
  },
  feedbackText: {
    margin: 0,
    fontSize: '14px',
    color: 'var(--color-text)',
    lineHeight: '1.7',
  },
  alphabetRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '4px',
    justifyContent: 'center',
    width: '100%',
    maxWidth: '520px',
    padding: '8px',
    background: 'var(--color-surface-solid)',
    borderRadius: '12px',
    border: '1px solid var(--color-border)',
    boxSizing: 'border-box',
  },
  alphaBtn: {
    width: '34px',
    height: '34px',
    border: '1px solid var(--color-border)',
    borderRadius: '8px',
    background: 'var(--color-btn-alpha-bg)',
    fontSize: '18px',
    cursor: 'pointer',
    color: 'var(--color-text)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  alphaBtnActive: {
    background: 'var(--color-form-active-bg)',
    color: '#fff8ee',
    border: '1px solid var(--color-accent)',
    boxShadow: '0 2px 8px var(--color-shadow-deep)',
  },
  completedBadge: {
    display: 'inline-block',
    marginLeft: '10px',
    fontSize: '10px',
    background: 'var(--color-accent-warm)',
    color: 'var(--color-text-muted)',
    padding: '2px 8px',
    borderRadius: '20px',
    border: '1px solid var(--color-border)',
    verticalAlign: 'middle',
    letterSpacing: '.04em',
  },
  dotComplete: {
    position: 'absolute',
    bottom: '3px',
    right: '3px',
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    background: 'var(--color-dot-complete)',
    display: 'block',
  },
  dotStarted: {
    position: 'absolute',
    bottom: '3px',
    right: '3px',
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    background: 'var(--color-dot-started)',
    display: 'block',
  },
  historyToggle: {
    background: 'none',
    border: 'none',
    padding: '6px 2px',
    fontSize: '12px',
    color: 'var(--color-text-muted)',
    cursor: 'pointer',
    width: '100%',
    textAlign: 'left',
    letterSpacing: '.03em',
  },
  historyPanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    paddingBottom: '4px',
  },
  historyEntry: {
    background: 'var(--color-surface)',
    border: '1px solid var(--color-border)',
    borderRadius: '10px',
    padding: '10px 14px',
  },
  historyDate: {
    fontSize: '10px',
    color: 'var(--color-text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '.1em',
    marginBottom: '6px',
  },
  historyText: {
    margin: 0,
    fontSize: '13px',
    color: 'var(--color-text)',
    lineHeight: '1.65',
  },
  offlineBanner: {
    width: '100%',
    maxWidth: '520px',
    background: 'var(--color-offline-bg)',
    border: '1px solid var(--color-border-strong)',
    borderRadius: '8px',
    padding: '8px 14px',
    fontSize: '12px',
    color: 'var(--color-accent)',
    textAlign: 'center',
    boxSizing: 'border-box',
  },

  /* ─── Header buttons row ─────────────────────────────── */
  headerButtons: {
    position: 'absolute',
    top: 0,
    right: 0,
    display: 'flex',
    gap: '4px',
    alignItems: 'center',
  },

  /* ─── Lesson mode toggle ─────────────────────────────── */
  lessonToggle: {
    background: 'none',
    border: '1px solid transparent',
    fontSize: '16px',
    cursor: 'pointer',
    padding: '3px 6px',
    borderRadius: '6px',
    transition: 'all .15s',
  },
  lessonToggleActive: {
    background: 'var(--color-btn-showme-bg)',
    border: '1px solid var(--color-border)',
  },
  lessonBanner: {
    width: '100%',
    maxWidth: '520px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '6px 14px',
    background: 'var(--color-btn-showme-bg)',
    borderRadius: '8px',
    border: '1px solid var(--color-border)',
    boxSizing: 'border-box',
  },
  lessonGroupName: {
    fontSize: '13px',
    fontWeight: '700',
    color: 'var(--color-primary)',
  },
  lessonGroupDesc: {
    fontSize: '11px',
    color: 'var(--color-text-muted)',
    fontStyle: 'italic',
  },

  /* ─── Comparison view ────────────────────────────────── */
  comparisonWrap: {
    width: '100%',
    maxWidth: '520px',
    display: 'flex',
    gap: '10px',
    boxSizing: 'border-box',
  },
  comparisonPane: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '6px',
  },
  comparisonLabel: {
    fontSize: '10px',
    textTransform: 'uppercase',
    letterSpacing: '.15em',
    color: 'var(--color-text-muted)',
  },
  comparisonRef: {
    width: '100%',
    aspectRatio: '1/1',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'var(--color-canvas-bg)',
    borderRadius: '12px',
    border: '2px solid var(--color-border)',
    fontSize: '140px',
    color: 'var(--color-primary)',
    direction: 'rtl',
    lineHeight: 1.2,
  },
  comparisonAttempt: {
    width: '100%',
    aspectRatio: '1/1',
    borderRadius: '12px',
    border: '2px solid var(--color-border)',
    background: 'var(--color-canvas-bg)',
    objectFit: 'contain',
  },
  comparisonToggle: {
    background: 'none',
    border: '1px solid var(--color-border)',
    borderRadius: '8px',
    padding: '6px 14px',
    fontSize: '12px',
    color: 'var(--color-accent)',
    cursor: 'pointer',
    letterSpacing: '.03em',
  },

  /* ─── Mode tabs (Letters / Words) ──────────────────────── */
  modeTabs: {
    display: 'flex',
    gap: '6px',
    width: '100%',
    maxWidth: '520px',
  },
  modeTab: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '8px 12px',
    borderRadius: '10px',
    border: '1.5px solid var(--color-border)',
    background: 'var(--color-surface-solid)',
    fontSize: '13px',
    fontWeight: '600',
    color: 'var(--color-accent)',
    cursor: 'pointer',
    letterSpacing: '.04em',
    transition: 'all .15s',
  },
  modeTabActive: {
    background: 'var(--color-form-active-bg)',
    border: '1.5px solid var(--color-accent)',
    color: '#fff8ee',
    boxShadow: '0 2px 8px var(--color-shadow-deep)',
  },

  /* ─── Word buttons in bottom row ─────────────────────── */
  wordBtn: {
    minWidth: '50px',
    height: '34px',
    border: '1px solid var(--color-border)',
    borderRadius: '8px',
    background: 'var(--color-btn-alpha-bg)',
    fontSize: '16px',
    cursor: 'pointer',
    color: 'var(--color-text)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0 10px',
    position: 'relative',
  },

  /* ─── Save / Share buttons ───────────────────────────── */
  btnSave: {
    background: 'var(--color-btn-clear-bg)',
    color: 'var(--color-accent)',
    border: '1px solid var(--color-border)',
    flex: '1',
  },
  btnShare: {
    background: 'var(--color-btn-nav-bg)',
    color: 'var(--color-primary)',
    border: '1px solid var(--color-border)',
    flex: '1',
  },

  /* ─── Review dashboard ────────────────────────────────── */
  reviewDash: {
    width: '100%',
    maxWidth: '520px',
    background: 'var(--color-surface-solid)',
    border: '1px solid var(--color-border)',
    borderRadius: '12px',
    padding: '16px 18px',
    boxSizing: 'border-box',
  },
  reviewHeader: {
    fontSize: '11px',
    textTransform: 'uppercase',
    letterSpacing: '.2em',
    color: 'var(--color-text-muted)',
    marginBottom: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  reviewHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  reviewResetBtn: {
    background: 'none',
    border: '1px solid var(--color-border)',
    borderRadius: '6px',
    padding: '4px 10px',
    fontSize: '11px',
    textTransform: 'none',
    letterSpacing: '0',
    color: 'var(--color-accent)',
    cursor: 'pointer',
  },
  reviewCount: {
    display: 'inline-block',
    background: 'var(--color-accent)',
    color: '#fff',
    fontSize: '11px',
    fontWeight: '700',
    padding: '1px 7px',
    borderRadius: '20px',
    letterSpacing: '0',
    textTransform: 'none',
  },
  reviewEmpty: {
    textAlign: 'center',
    color: 'var(--color-text-soft)',
    fontSize: '14px',
    padding: '28px 0',
    lineHeight: 1.6,
  },
  reviewGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    justifyContent: 'center',
  },
  reviewTileWrap: {
    position: 'relative',
  },
  reviewTile: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '2px',
    width: '68px',
    padding: '10px 4px',
    borderRadius: '10px',
    borderWidth: '1.5px',
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    background: 'var(--color-surface)',
    cursor: 'pointer',
    transition: 'all .15s',
  },
  reviewTileRemove: {
    position: 'absolute',
    top: '-6px',
    right: '-6px',
    width: '18px',
    height: '18px',
    borderRadius: '50%',
    border: '1px solid var(--color-border)',
    background: 'var(--color-surface-solid)',
    color: 'var(--color-text-muted)',
    fontSize: '11px',
    lineHeight: '16px',
    padding: '0',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewTileChar: {
    fontSize: '32px',
    color: 'var(--color-primary)',
    lineHeight: 1.3,
    direction: 'rtl',
  },
  reviewTileName: {
    fontSize: '9px',
    color: 'var(--color-text-muted)',
    textAlign: 'center',
    letterSpacing: '.03em',
  },
  reviewTileForm: {
    fontSize: '8px',
    color: 'var(--color-accent)',
    textTransform: 'uppercase',
    letterSpacing: '.06em',
    textAlign: 'center',
  },

  /* ─── Score stars ─────────────────────────────────────── */
  scoreRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    marginBottom: '8px',
  },
  starFilled: {
    fontSize: '20px',
    color: 'var(--color-star-filled)',
  },
  starEmpty: {
    fontSize: '20px',
    color: 'var(--color-star-empty)',
  },
  scoreLabel: {
    fontSize: '11px',
    color: 'var(--color-text-muted)',
    marginLeft: '6px',
  },

  /* ─── Theme selector ─────────────────────────────────── */
  themeRow: {
    display: 'flex',
    gap: '6px',
    flexWrap: 'wrap',
    width: '100%',
  },
  themeBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '6px 10px',
    borderRadius: '8px',
    border: '1.5px solid var(--color-border)',
    background: 'var(--color-surface-solid)',
    fontSize: '12px',
    color: 'var(--color-text)',
    cursor: 'pointer',
    fontFamily: "'Georgia',serif",
  },
  themeBtnActive: {
    border: '1.5px solid var(--color-accent)',
    background: 'var(--color-btn-showme-bg)',
  },
  themeSwatch: {
    width: '14px',
    height: '14px',
    borderRadius: '4px',
    border: '1px solid var(--color-border)',
    flexShrink: 0,
  },

  /* ─── Brush swatches ─────────────────────────────────── */
  brushRow: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  brushSwatch: {
    width: '22px',
    height: '22px',
    borderRadius: '50%',
    border: '2px solid transparent',
    cursor: 'pointer',
    transition: 'transform .1s, border-color .15s',
    flexShrink: 0,
  },
  brushSwatchActive: {
    border: '2px solid var(--color-accent)',
    boxShadow: '0 0 0 2px var(--color-surface-solid)',
  },

  /* ─── Settings divider ───────────────────────────────── */
  settingsDivider: {
    width: '100%',
    height: '1px',
    background: 'var(--color-border)',
    margin: '4px 0',
  },

  /* ─── Analytics panel ────────────────────────────────── */
  analyticsPanel: {
    width: '100%',
    maxWidth: '520px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  analyticsCard: {
    background: 'var(--color-surface-solid)',
    border: '1px solid var(--color-border)',
    borderRadius: '12px',
    padding: '14px 16px',
    boxSizing: 'border-box',
  },
  analyticsCardTitle: {
    fontSize: '11px',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: '.18em',
    color: 'var(--color-text-muted)',
    marginBottom: '12px',
  },
  analyticsStreakRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-around',
    gap: '8px',
  },
  analyticsStreakItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
    flex: 1,
  },
  analyticsStreakNumber: {
    fontSize: '28px',
    fontWeight: '700',
    color: 'var(--color-primary)',
    fontFamily: "'Georgia',serif",
    lineHeight: 1,
  },
  analyticsStreakLabel: {
    fontSize: '10px',
    color: 'var(--color-text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '.08em',
  },
  analyticsStreakDivider: {
    width: '1px',
    height: '32px',
    background: 'var(--color-border)',
  },
  analyticsFreezeRow: {
    marginTop: '10px',
    textAlign: 'center',
  },
  analyticsFreezeAvailable: {
    fontSize: '10px',
    textTransform: 'uppercase',
    letterSpacing: '.08em',
    color: 'var(--color-dot-complete)',
    fontWeight: '600',
  },
  analyticsFreezeUsed: {
    fontSize: '10px',
    textTransform: 'uppercase',
    letterSpacing: '.08em',
    color: 'var(--color-text-muted)',
  },
  analyticsScoreBig: {
    fontSize: '32px',
    fontWeight: '700',
    color: 'var(--color-primary)',
    fontFamily: "'Georgia',serif",
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  analyticsScoreStars: {
    fontSize: '18px',
  },
  analyticsBarChart: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  analyticsBarRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '12px',
  },
  analyticsBarLabel: {
    width: '24px',
    textAlign: 'right',
    color: 'var(--color-text-muted)',
    flexShrink: 0,
  },
  analyticsBarTrack: {
    flex: 1,
    height: '8px',
    background: 'var(--color-btn-clear-bg)',
    borderRadius: '4px',
    overflow: 'hidden',
  },
  analyticsBarFill: {
    height: '100%',
    background: 'var(--color-accent)',
    borderRadius: '4px',
    transition: 'width .3s ease',
  },
  analyticsBarValue: {
    width: '20px',
    textAlign: 'left',
    color: 'var(--color-text-soft)',
    flexShrink: 0,
  },
  analyticsHeatmapGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '4px',
    justifyContent: 'center',
  },
  analyticsHeatmapCell: {
    width: '34px',
    height: '34px',
    border: '1px solid var(--color-border)',
    borderRadius: '8px',
    background: 'var(--color-accent)',
    fontSize: '18px',
    cursor: 'pointer',
    color: '#fff8ee',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  analyticsWeakList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  analyticsWeakItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 10px',
    borderRadius: '8px',
    border: '1px solid var(--color-border)',
    background: 'var(--color-surface)',
    cursor: 'pointer',
    color: 'var(--color-text)',
    fontSize: '13px',
  },
  analyticsWeakChar: {
    fontSize: '20px',
    color: 'var(--color-primary)',
    lineHeight: 1,
    direction: 'rtl',
  },
  analyticsWeakName: {
    fontWeight: '600',
    minWidth: '48px',
  },
  analyticsWeakForm: {
    fontSize: '10px',
    color: 'var(--color-text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '.06em',
    flex: 1,
  },
  analyticsWeakScore: {
    fontWeight: '700',
    color: 'var(--color-accent)',
    fontSize: '12px',
  },
  analyticsTimeline: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: '2px',
    height: '80px',
    paddingBottom: '18px',
    position: 'relative',
  },
  analyticsTimelineCol: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-end',
    height: '100%',
    position: 'relative',
  },
  analyticsTimelineBarWrap: {
    width: '100%',
    height: '60px',
    display: 'flex',
    alignItems: 'flex-end',
  },
  analyticsTimelineBar: {
    width: '100%',
    background: 'var(--color-accent)',
    borderRadius: '2px 2px 0 0',
    opacity: 0.7,
    transition: 'height .3s ease',
    minHeight: '2px',
  },
  analyticsTimelineFrozenBar: {
    width: '100%',
    background: 'var(--color-dot-complete)',
    borderRadius: '2px 2px 0 0',
    opacity: 0.5,
    height: '20%',
    minHeight: '4px',
    transition: 'height .3s ease',
  },
  analyticsTimelineLabel: {
    position: 'absolute',
    bottom: '-16px',
    fontSize: '8px',
    color: 'var(--color-text-muted)',
    whiteSpace: 'nowrap',
  },

  /* ─── Achievements (Stats tab) ───────────────────────── */
  analyticsAchTitleRow: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: '8px',
  },
  analyticsAchCount: {
    fontSize: '11px',
    fontWeight: '700',
    letterSpacing: '.1em',
    color: 'var(--color-accent)',
    whiteSpace: 'nowrap',
  },
  analyticsAchGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(76px, 1fr))',
    gap: '8px',
  },
  analyticsAchTile: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: '3px',
    padding: '10px 6px 8px',
    borderRadius: '10px',
    border: '1px solid var(--color-border)',
    background: 'var(--color-surface)',
    textAlign: 'center',
    minWidth: 0,
    minHeight: '86px',
    boxSizing: 'border-box',
  },
  analyticsAchTileEarned: {
    borderColor: 'var(--color-accent-light)',
    background: 'var(--color-progress-badge-bg)',
  },
  analyticsAchTileLocked: {
    opacity: 0.45,
    filter: 'grayscale(1)',
  },
  analyticsAchIcon: {
    fontSize: '22px',
    lineHeight: 1,
    color: 'var(--color-accent)',
  },
  analyticsAchName: {
    fontSize: '11px',
    fontWeight: '600',
    color: 'var(--color-text)',
    lineHeight: 1.25,
  },
  analyticsAchDesc: {
    fontSize: '9px',
    color: 'var(--color-text-muted)',
    lineHeight: 1.3,
  },
  analyticsAchDate: {
    fontSize: '9px',
    fontWeight: '600',
    color: 'var(--color-dot-complete)',
    letterSpacing: '.03em',
    whiteSpace: 'nowrap',
  },

  /* ─── XP / level badge (header) ──────────────────────── */
  levelBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '3px 8px 3px 6px',
    borderRadius: '20px',
    border: '1px solid var(--color-border)',
    background: 'var(--color-progress-badge-bg)',
    flexShrink: 0,
    title: '', // (no-op; titles set via JSX)
  },
  levelBadgeIcon: {
    fontSize: '12px',
    color: 'var(--color-accent-warm)',
    lineHeight: 1,
  },
  levelBadgeNum: {
    fontSize: '11px',
    fontWeight: 700,
    color: 'var(--color-text)',
    letterSpacing: '.02em',
  },
  levelBadgeBar: {
    width: '28px',
    height: '4px',
    borderRadius: '2px',
    background: 'var(--color-btn-clear-bg)',
    overflow: 'hidden',
  },
  levelBadgeBarFill: {
    height: '100%',
    background: 'var(--color-accent)',
    borderRadius: '2px',
    transition: 'width .3s ease',
  },

  /* ─── XP card (Stats tab) ────────────────────────────── */
  xpCard: {
    background: 'var(--color-surface-solid)',
    border: '1px solid var(--color-border)',
    borderRadius: '12px',
    padding: '14px 16px',
    boxSizing: 'border-box',
  },
  xpCardTitle: {
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '.18em',
    color: 'var(--color-text-muted)',
    marginBottom: '12px',
  },
  xpCardRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  xpCardLevel: {
    fontSize: '32px',
    fontWeight: 700,
    color: 'var(--color-primary)',
    fontFamily: "'Georgia',serif",
    lineHeight: 1,
    minWidth: '48px',
  },
  xpCardBarWrap: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  xpCardBar: {
    width: '100%',
    height: '10px',
    borderRadius: '5px',
    background: 'var(--color-btn-clear-bg)',
    overflow: 'hidden',
  },
  xpCardBarFill: {
    height: '100%',
    background: 'var(--color-accent)',
    borderRadius: '5px',
    transition: 'width .4s ease',
  },
  xpCardTotal: {
    fontSize: '11px',
    color: 'var(--color-text-muted)',
    letterSpacing: '.04em',
  },
  xpCardHint: {
    fontSize: '11px',
    color: 'var(--color-text-soft)',
    marginTop: '8px',
  },

  /* ─── Decks (Review sub-tab) ─────────────────────────── */
  deckSubNav: {
    display: 'flex',
    gap: '6px',
    marginBottom: '12px',
    maxWidth: '520px',
    width: '100%',
  },
  deckSubNavBtn: {
    flex: 1,
    padding: '8px 12px',
    borderRadius: '8px',
    border: '1.5px solid var(--color-border)',
    background: 'var(--color-surface)',
    color: 'var(--color-text)',
    fontSize: '12px',
    fontWeight: '600',
    letterSpacing: '.04em',
    cursor: 'pointer',
    transition: 'all .15s',
  },
  deckSubNavBtnActive: {
    background: 'var(--color-form-active-bg)',
    color: '#fff8ee',
    borderColor: 'var(--color-accent)',
  },
  deckRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '12px 14px',
    borderRadius: '10px',
    border: '1px solid var(--color-border)',
    background: 'var(--color-surface)',
    marginBottom: '8px',
  },
  deckRowName: {
    flex: 1,
    fontSize: '15px',
    fontWeight: '600',
    color: 'var(--color-text)',
  },
  deckRowCount: {
    fontSize: '11px',
    color: 'var(--color-text-muted)',
  },
  deckEditorItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '8px 12px',
    borderRadius: '8px',
    border: '1px solid var(--color-border)',
    background: 'var(--color-surface)',
    marginBottom: '6px',
  },
  deckEditorItemChar: {
    fontSize: '28px',
    color: 'var(--color-primary)',
    lineHeight: 1.2,
    direction: 'rtl',
    minWidth: '32px',
    textAlign: 'center',
  },
  deckEditorItemLabel: {
    flex: 1,
    fontSize: '13px',
    color: 'var(--color-text)',
  },
  deckPickerGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    justifyContent: 'center',
    marginTop: '12px',
  },
  deckPickerWordRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '8px 12px',
    borderRadius: '8px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    background: 'var(--color-surface)',
    marginBottom: '6px',
  },
  deckPickerWordChar: {
    fontSize: '24px',
    color: 'var(--color-primary)',
    direction: 'rtl',
    minWidth: '120px',
  },
  deckPickerWordMeta: {
    flex: 1,
    fontSize: '12px',
    color: 'var(--color-text-muted)',
  },

  /* ─── Deck polish ─────────────────────────────────────── */
  deckSessionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  deckSessionName: {
    fontSize: 14,
    fontWeight: '600',
    color: 'var(--color-text)',
  },
  deckSessionModeChip: {
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: '.06em',
    textTransform: 'uppercase',
    padding: '2px 8px',
    borderRadius: 99,
    marginLeft: 8,
  },
  deckModeChipFull: {
    background: 'rgba(var(--color-accent-rgb, 192,112,58),0.15)',
    color: 'var(--color-accent)',
  },
  deckModeChipLowScore: {
    background: 'rgba(90,158,78,0.15)',
    color: 'rgb(90,158,78)',
  },
  deckSummarySubtitle: {
    fontSize: 13,
    color: 'var(--color-text-soft)',
    marginBottom: 12,
  },
  deckSummaryButtons: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  deckSummaryChipForm: {
    fontSize: 9,
    opacity: 0.6,
    display: 'block',
    lineHeight: 1.1,
  },
  deckRowMeta: {
    fontSize: 11,
    color: 'var(--color-text-muted)',
    marginTop: 2,
  },
  deckRowActions: {
    display: 'flex',
    gap: 4,
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'flex-end',
    maxWidth: '60%',
  },
  deckRowActionSmall: {
    fontSize: 11,
    padding: '3px 7px',
    borderRadius: 6,
  },
  deckBulkBar: {
    display: 'flex',
    gap: 6,
    flexWrap: 'wrap',
    marginBottom: 12,
  },
  deckBulkBtn: {
    fontSize: 11,
    padding: '4px 10px',
    borderRadius: 6,
    border: '1px solid var(--color-border)',
    background: 'var(--color-surface)',
    color: 'var(--color-text)',
    cursor: 'pointer',
    transition: 'all .15s',
  },
  deckSearchInput: {
    width: '100%',
    padding: '8px 12px',
    borderRadius: 8,
    border: '1px solid var(--color-border)',
    background: 'var(--color-surface)',
    color: 'var(--color-text)',
    fontSize: 14,
    boxSizing: 'border-box',
    marginBottom: 12,
  },
  deckPickerCheckmark: {
    position: 'absolute',
    top: 2,
    right: 2,
    fontSize: 12,
    color: 'var(--color-accent)',
    fontWeight: '700',
  },
  deckPickerTileWrap: {
    position: 'relative',
  },
  undoToast: {
    position: 'fixed',
    bottom: 24,
    left: '50%',
    transform: 'translateX(-50%)',
    maxWidth: 520,
    width: 'calc(100% - 32px)',
    padding: '12px 16px',
    background: 'var(--color-card-bg)',
    border: '1px solid var(--color-border)',
    borderRadius: 12,
    boxShadow: '0 4px 20px rgba(0,0,0,0.15)',
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    zIndex: 1000,
  },
  undoToastMessage: {
    flex: 1,
    fontSize: 14,
    color: 'var(--color-text)',
  },
  undoToastAction: {
    fontSize: 13,
    fontWeight: '600',
    padding: '6px 14px',
  },
  undoToastDismiss: {
    fontSize: 14,
    padding: '4px 8px',
    color: 'var(--color-text-muted)',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
  },
};

export default styles;
